# Generated by Django 5.2 on 2025-04-18 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courseName", models.CharField(max_length=256)),
                ("semester", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("userEmail", models.EmailField(max_length=254)),
                ("phoneNumber", models.IntegerField()),
                ("firstName", models.CharField(max_length=20)),
                ("lastName", models.CharField(max_length=20)),
                ("homeAddress", models.CharField(max_length=20)),
                ("officeHours", models.CharField(blank=True, max_length=20, null=True)),
                ("timeCreated", models.DateTimeField(auto_now_add=True)),
                ("accountType", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sectionCode", models.CharField(max_length=20)),
                ("instructor", models.CharField(max_length=256, blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TA_Scheduler_App.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graderStatus", models.IntegerField(default=0)),
                (
                    "sectionID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TA_Scheduler_App.section",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TA_Scheduler_App.user",
                    ),
                ),
            ],
        ),
    ]
